from math import pi, tan, tau

#WINDOW
X = 1600
Y = 900
HALF_X = X // 2
HALF_Y = Y // 2
WINDOW = X,Y
FPS = 60

#RAY CASTING:
NUM_RAYS = X//2
HALF_NUM_RAYS = NUM_RAYS//2
FOV = pi / 3
FOV_HALF = FOV / 2
DEL_RAY  = FOV / NUM_RAYS
DISTANCE = HALF_X/tan(FOV_HALF)
MAX_DEPTH = 20
SCALE = X // NUM_RAYS

TEX_SIZE = 256
TEX_SIZE_HALF = 256 / 2


#MOUSE
SENSITIVITY = 0.001

#BACK GROUND SETTINGS
ROTATE_SPEED = X / tau